### ISSUE TITLE
Need A Readme File

### ISSUE THREAD

**Issue by AshirbadGudu** [AshirbadGudu/html-css-js-carousel#2]
Create A Proper Readme File For The Repogitory

**Comment by Varshithvhegde** [comment]
> Create A Proper Readme File For The Repogitory 

I have made a pull request by creating Readme documentation. Merge the pull request.

**Comment by AshirbadGudu** [comment]
> > Create A Proper Readme File For The Repogitory
> 
> I have made a pull request by creating Readme documentation. Merge the pull request.

Great Work @Varshithvhegde, I really appreciate your effort.
